# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c80766e1e1214d9991b1046740de9f48c61e21c3ef3d8d56a955cb0189c624e8a60d964b478673df9f9434a22ad6f89f7c06fd8bc491499f67018557f3c878a9

test:
  secret_key_base: 96318faff6c61551923b5b0c59e6cfa179700c12b56bfcdb4752a8f6f73e7ad2cccd9b929d562a9677b2cd6f8f711dd72841c5eaf08a8bc108a91e9887e2dd50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
